---
driver:
  name: docker
<% if ENV['DOCKER_HOST'] %>
  socket: <%= ENV['DOCKER_HOST'] %>
#<% end %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: test-memcached
    run_list:
      - recipe[optoro_memcached::default]
    attributes:
